// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Lens$Rationale = require("rationale/src/Lens.js");
var GithubJson = require("hast-util-sanitize/lib/github.json");

var attributeLens = Lens$Rationale.make((function (prim) {
        return prim.attributes;
      }), (function (attributes, sch) {
        return Object.assign(sch, {
                    attributes: attributes
                  });
      }));

var codeLens = Lens$Rationale.make((function (prim) {
        return prim.code;
      }), (function (code, attr) {
        return Object.assign(attr, {
                    code: code
                  });
      }));

var sanitizeGhSchema = Lens$Rationale.over(Lens$Rationale.$great$great$neg(attributeLens, codeLens), (function () {
        return /* array */["className"];
      }), GithubJson);

console.log("github schema", GithubJson);

exports.attributeLens = attributeLens;
exports.codeLens = codeLens;
exports.sanitizeGhSchema = sanitizeGhSchema;
/* attributeLens Not a pure module */
