// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Markdown$ReactTemplate = require("./Markdown.bs.js");
var HelloWorldMd = require("./blogs/2018-12-5-hello-world.md");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Markdown$ReactTemplate.make(HelloWorldMd, /* array */[])), "main");

/*  Not a pure module */
