// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Remark = require("remark");
var RemarkParse = require("remark-parse");
var RemarkReact = require("remark-react");
var RemarkHighlightJs = require("remark-highlight.js");

var _renderer = Remark().use(RemarkParse).use(RemarkHighlightJs).use(RemarkReact);

function render(markdown) {
  return _renderer.processSync(markdown).contents;
}

exports._renderer = _renderer;
exports.render = render;
/* _renderer Not a pure module */
