// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Remark = require("remark");
var RemarkParse = require("remark-parse");
var RemarkReact = require("remark-react");
var RemarkCodeMirror = require("./RemarkCodeMirror");

var RemarkEngine = /* module */[];

var RemarkPlugin = /* module */[];

var RemarkParsePlugin = /* module */[];

var RemarkReactPlugin = /* module */[];

var _renderer = Remark().use(RemarkParse).use(RemarkReact, RemarkCodeMirror);

function render(markdown) {
  return _renderer.processSync(markdown).contents;
}

exports.RemarkEngine = RemarkEngine;
exports.RemarkPlugin = RemarkPlugin;
exports.RemarkParsePlugin = RemarkParsePlugin;
exports.RemarkReactPlugin = RemarkReactPlugin;
exports._renderer = _renderer;
exports.render = render;
/* _renderer Not a pure module */
